CI: yet another attempt to not build when nothing changes (s/pipeline/pipelines/); reduce verbosity of unzip; debug commit: delay since last commit is set to 0 seconds, to trigger it today

diff --git a/.gitlab-ci-inria.yml b/.gitlab-ci-inria.yml
--- a/.gitlab-ci-inria.yml
+++ b/.gitlab-ci-inria.yml
@@ -441,14 +441,15 @@ check_changes:
       when: never
     - if: '$CI_PIPELINE_SOURCE == "schedule"'
   tags:
-    - small  # Inria infra
+    - small
   script:
-  - if [ $(expr $(date +%s) - $(git log -1 --format=%ct)) -gt 86400 ] ;  then
+  - if [ $(expr $(date +%s) - $(git log -1 --format=%ct)) -gt 0 ] ;  then
       echo "No change in 24h. Canceling current pipeline..." ;
-      apt install -y curl ;
+      apt install -y curl ; set -x;
       curl --request POST --form token=$GITLAB_API_TOKEN
-        --form ref=$CI_COMMIT_REF_NAME
-        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipeline/$CI_PIPELINE_ID/cancel" ;
+        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel" ;
+      echo "Do not proceed even if we fail to cancel the job" ;
+      sleep 10; exit 1;
     else
       echo "Something was commited since yesterday. Proceed with the build." ;
     fi
@@ -498,18 +499,18 @@ sonarqube:
   - export SONAR_SCANNER_VERSION=7.0.2.4839
   - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
   - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
-  - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
+  - unzip -q -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
   - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
   - export SONAR_SCANNER_OPTS="-server"
   - curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
-  - unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
+  - unzip -q -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
   - export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
   # configure and build simgrid
   - cmake -GNinja -Denable_python=ON -Denable_java=ON -Denable_documentation=OFF -Denable_testsuite_smpi_MPICH3=ON -Denable_testsuite_McMini=ON -Denable_coverage=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
   - build-wrapper-linux-x86-64 --out-dir bw-output ninja all tests
   # Install Jacoco
   - wget https://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.8.12/jacoco-0.8.12.zip -O /tmp/jacoco.zip
-  - (cd /tmp ; unzip jacoco.zip)
+  - (cd /tmp ; unzip -q jacoco.zip)
   - export JACOCO_PATH=/tmp/lib
   - export JAVA_TOOL_OPTIONS="-javaagent:${JACOCO_PATH}/jacocoagent.jar"
   # run the tests
