gitlab ci: setup smoke tests + a cache on regular builds and flag builds

diff --git a/.gitlab-ci-inria.yml b/.gitlab-ci-inria.yml
--- a/.gitlab-ci-inria.yml
+++ b/.gitlab-ci-inria.yml
@@ -1,28 +1,5 @@
 # gitlab-ci-local --file .gitlab-ci-inria.yml  <job>
 
-image: simgrid/build-deps
-
-# On Inria, we run the base build all the time 
-build-base:
-  rules:
-    - if: '$CI_COMMIT_BRANCH == "stable"'
-      when: never
-    - if: '$CI_PIPELINE_SOURCE == "push"'
-  tags:
-    - large  # Inria infra
-  script:
-  - apt-get --allow-releaseinfo-change update
-  - apt install -y ninja-build libgcc-12-dev libgraphviz-dev nlohmann-json3-dev default-jdk-headless libns3-dev
-  - rm -rf CMakeFiles CMakeCache.txt
-  - cmake -GNinja -Denable_python=ON -Denable_java=ON -Denable_documentation=OFF -Denable_testsuite_smpi_MPICH3=ON -Denable_testsuite_McMini=ON -Denable_compile_warnings=ON -DLTO_EXTRA_FLAG="auto" .
-  - ninja --verbose all tests
-  - ctest -T Test --output-junit result.xml -j$(nproc) --output-on-failure
-  artifacts:
-    when: always
-    expire_in: 6 months
-    reports:
-      junit: result.xml
-
 coverage:
   image: debian:testing
   rules:
@@ -58,8 +35,63 @@ coverage:
         path: ./*_coverage.xml
       junit: result.xml
 
+# ###################################################################################################
+# ###################################################################################################
+# ###################################################################################################
+
+stages:
+ - smoke_test
+ - test
+# Smoke tests are fast jobs. If they fail, no need to run the other tests 
+
+.cached-build:
+  artifacts:
+    when: on_failure
+    untracked: true
+  # Use ccache transparently, and print stats before/after
+  before_script:
+    - export PATH="/usr/lib/ccache:$PATH"
+    - export CCACHE_BASEDIR="$PWD"
+    - export CCACHE_DIR="$PWD/ccache"
+    - export CCACHE_COMPILERCHECK=content
+    - ccache --zero-stats || true
+    - ccache --show-stats || true
+  after_script:
+    - export CCACHE_DIR="$PWD/ccache"
+    - ccache --show-stats
+
+image: simgrid/build-deps
+
+# On Inria, we run the base build all the time 
+build-base:
+  extends: .cached-build
+  stage: smoke_test
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "stable"'
+      when: never
+    - if: '$CI_PIPELINE_SOURCE == "push"'
+  tags:
+    - large  # Inria infra
+  script:
+  - apt-get --allow-releaseinfo-change update
+  - rm -rf CMakeFiles CMakeCache.txt
+  - cmake -GNinja -Denable_python=ON -Denable_java=ON -Denable_documentation=OFF -Denable_testsuite_smpi_MPICH3=ON -Denable_testsuite_McMini=ON -Denable_compile_warnings=ON -DLTO_EXTRA_FLAG="auto" .
+  - ninja --verbose all tests
+  - ctest -T Test --output-junit result.xml -j$(nproc) --output-on-failure
+  artifacts:
+    when: always
+    expire_in: 6 months
+    reports:
+      junit: result.xml
+
+
 # Ensure that the produced tarball is OK
 distcheck:
+  stage: smoke_test
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "stable"'
+      when: never
+    - if: '$CI_PIPELINE_SOURCE == "push"'
   tags:
     - linux  # any runner will do
   script:
@@ -68,12 +100,13 @@ distcheck:
 
 # Test the Python build
 build-pip:
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
     - if: '$CI_PIPELINE_SOURCE == "push"'
   tags: # Select a runner
-    - small # Inria infra
+    - medium # Inria infra
   script:
   - apt-get --allow-releaseinfo-change update
   - apt install -y python3-pip cmake libboost-dev g++ gcc pybind11-dev python3-build python3.11-venv
@@ -89,6 +122,7 @@ build-pip:
 
 alpine-release:
   image: alpine:latest
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -109,6 +143,7 @@ alpine-release:
 
 debian-clang:
   image: debian:testing
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -130,6 +165,7 @@ debian-clang:
 
 fedora-rawhide-release:
   image: fedora:rawhide
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -150,6 +186,7 @@ fedora-rawhide-release:
 
 rocky-release:
   image: rockylinux:9
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -173,6 +210,7 @@ rocky-release:
 
 opensuse-release:
   image: opensuse/tumbleweed # tumbleweed is the rolling release with recent software
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -193,6 +231,7 @@ opensuse-release:
 
 opensuse-intelCC:
   image: opensuse/tumbleweed # tumbleweed is the rolling release with recent software
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -214,6 +253,7 @@ opensuse-intelCC:
 
 arch-release:
   image: archlinux:latest
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -238,6 +278,8 @@ arch-release:
 # ###################################################################################################
 
 flags:
+  extends: .cached-build
+  stage: test
   rules:
     - if: '$CI_COMMIT_BRANCH == "stable"'
       when: never
@@ -250,9 +292,6 @@ flags:
         SMPI: ["SMPI", "NO_SMPI"]
         DEBUG: ["DEBUG", "NO_DEBUG"]
   script:
-  - apt-get --allow-releaseinfo-change update
-  - apt install -y ninja-build libgcc-12-dev libgraphviz-dev nlohmann-json3-dev default-jdk-headless libns3-dev
-  - rm -rf CMakeFiles CMakeCache.txt
   - export CXXFLAGS=-D_GLIBCXX_DEBUG
   # We cannot put ON/OFF as values directly, or the job name is not instructive
   - if [ ${MC} == "MC" ]       ; then BUILD_MC="ON"    ; else BUILD_MC="OFF"    ; fi
@@ -264,4 +303,3 @@ flags:
   - if [ "${BUILD_MC}/${BUILD_SMPI}/${BUILD_DEBUG}" = "ON/ON/ON" ]; then
      ctest -T Test --output-junit result.xml -j$(nproc) --output-on-failure
     fi
-
