At last, not rerunning the pipeline when nothing changed seems to work

diff --git a/.gitlab-ci-inria.yml b/.gitlab-ci-inria.yml
--- a/.gitlab-ci-inria.yml
+++ b/.gitlab-ci-inria.yml
@@ -444,12 +444,13 @@ check_changes:
     - small
   script:
   - |
-    if [ $(expr $(date +%s) - $(git log -1 --format=%ct)) -gt 0 ] ;  then
+    if [ $(expr $(date +%s) - $(git log -1 --format=%ct)) -gt 86400 ] ;  then
       echo "No change in 24h. Canceling current pipeline..." ;
       apt install -y curl ; set -x;
       curl --request POST  --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel" ;
-      echo "Do not proceed even if we fail to cancel the job" ;
-      sleep 10; exit 1;
+      sleep 10;
+      echo "Canceling the job failed; fail it instead" ;
+      exit 1;
     else
       echo "Something was commited since yesterday. Proceed with the build." ;
     fi
