Make it easy to specify the version of automake to use (it's 1.7 here on graal)
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/simgrid/simgrid/trunk@144 48e7efb5-ca39-0410-a469-dd3cf9ba447f

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -8,7 +8,9 @@
 PKG_NAME="GRAS"
 # a list of all dirs containing possibly some macros
 acmacrodirs="${HOME}/share/aclocal ${PWD}/acmacro /usr/share/aclocal/gnome2-macros"
- 
+
+amver=1.7
+
 ######
 ###### End of conf part
 ######
@@ -57,10 +59,10 @@ DIE=0
   }
 }
 
-(automake-1.8 --version) < /dev/null > /dev/null 2>&1 || {
+(automake-$amver --version) < /dev/null > /dev/null 2>&1 || {
   echo
-  echo "**Error**: You must have \`automake' 1.8 installed to compile $PKG_NAME."
-  echo "Get ftp://ftp.gnu.org/pub/gnu/automake-1.8.tar.gz"
+  echo "**Error**: You must have \`automake' $amver installed to compile $PKG_NAME."
+  echo "Get ftp://ftp.gnu.org/pub/gnu/automake-amver.tar.gz"
   echo "(or a newer version if it is available)"
   DIE=1
   NO_AUTOMAKE=yes
@@ -137,15 +139,15 @@ do
 	libtoolize --force --copy || exit 1
       fi
     fi
-    echo "Running aclocal-1.8 $aclocalinclude..."
-    aclocal-1.8 $aclocalinclude 
+    echo "Running aclocal-$amver $aclocalinclude..."
+    aclocal-$amver $aclocalinclude 
     if grep "^AM_CONFIG_HEADER" $configfile >/dev/null; then
       echo "Running autoheader in "`pwd`"..."
       autoheader || exit 1
     fi
     if grep "^AM_INIT_AUTOMAKE" $configfile >/dev/null; then
-      echo "Running automake-1.8 --gnu --add-missing $am_opt ..."
-      automake-1.8 --gnu --add-missing $am_opt || exit 1
+      echo "Running automake-$amver --gnu --add-missing $am_opt ..."
+      automake-$amver --gnu --add-missing $am_opt || exit 1
     fi
     echo "Running autoconf..."
     autoconf || exit 1
