Checks that theoriticians didn't forget to install the right packages to use the CVS version (hello PF)
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/simgrid/simgrid/trunk@2884 48e7efb5-ca39-0410-a469-dd3cf9ba447f

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,6 +3,26 @@
 
 amver=1.9
 
+
+lt=`which libtoolize`
+if [ "x$lt" = "x" ] ; then
+  echo "Libtool not found. Please install the libtool package to proceed with a CVS checkout"
+  exit 1
+fi
+
+am=`which automake-$amver`
+if [ "x$am" = "x" ] ; then
+  echo "automake version $amver not found. Please install the relevant package to proceed with a CVS checkout"
+  exit 1
+fi
+
+ac=`which autoconf`
+if [ "x$ac" = "x" ] ; then
+  echo "autoconf not found. Please install the relevant package to proceed with a CVS checkout"
+  exit 1
+fi
+
+
 # AUTOCONF=
 # AUTOHEADER=
 # AUTOPOINT=
