make it easier to write tesh files by removing the full path to scripts from logs

diff --git a/src/smpi/smpirun.in b/src/smpi/smpirun.in
--- a/src/smpi/smpirun.in
+++ b/src/smpi/smpirun.in
@@ -79,7 +79,7 @@ while true; do
         "-platform")
 	    PLATFORM="$2"
             if [ ! -f "${PLATFORM}" ]; then
-		echo "[$0] ** error: the file '${PLATFORM}' does not exist. Aborting."
+		echo "[`basename $0`] ** error: the file '${PLATFORM}' does not exist. Aborting."
 		exit 1
             fi
 	    shift 2
@@ -87,7 +87,7 @@ while true; do
         "-hostfile")
 	    HOSTFILE="$2"
             if [ ! -f "${HOSTFILE}" ]; then
-		echo "[$0] ** error: the file '${HOSTFILE}' does not exist. Aborting."
+		echo "[`basename $0`] ** error: the file '${HOSTFILE}' does not exist. Aborting."
 		exit 1
             fi
 	    shift 2
@@ -96,7 +96,7 @@ while true; do
         "-machinefile")
 	    HOSTFILE="$2"
             if [ ! -f "${HOSTFILE}" ]; then
-		echo "[$0] ** error: the file '${HOSTFILE}' does not exist. Aborting."
+		echo "[`basename $0`] ** error: the file '${HOSTFILE}' does not exist. Aborting."
 		exit 1
             fi
 	    shift 2
@@ -245,7 +245,7 @@ fi
 # Don't use wc -l to compute it to avoid issues with trailing \n at EOF
 hostfile_procs=`grep -c "[a-zA-Z0-9]" $HOSTFILE`
 if [ ${hostfile_procs} = 0 ] ; then
-   echo "[$0] ** error: the hostfile '${HOSTFILE}' is empty. Aborting." >&2
+   echo "[`basename $0`] ** error: the hostfile '${HOSTFILE}' is empty. Aborting." >&2
    exit 1
 fi
 
